# Generated by Django 4.2.5 on 2024-01-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('Size', 'size')], max_length=20)),
                ('variation_value', models.CharField(choices=[('Red', 'red'), ('Yellow', 'yellow'), ('Green', 'green'), ('Black', 'black')], max_length=200)),
                ('is_active', models.CharField(default=True, max_length=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
