# Generated by Django 5.0.1 on 2024-02-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_note_order_order_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_notes',
            new_name='order_note',
        ),
    ]
